# Generated by Django 5.0 on 2023-12-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_product_is_active_productline"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
