# Generated by Django 5.0 on 2024-01-02 12:56

import drfecommerce.product.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_brand_is_active_category_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="order",
            field=drfecommerce.product.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
