# Generated by Django 5.0 on 2024-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_productline_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
